name: feature

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix'
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'

jobs:
  feature:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.2"

      - name: Install pipenv
        run: make install

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: make init

      - name: Run analyzer
        run: make analyze

      - name: Run test suite
        run: make tests

      - name: Upload test results (junit)
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: pytest-results
          path: junit/test-results.xml

      - name: Upload test results (html)
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: pytest-html
          path: htmlcov
