name: start-release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.2"

      - name: Install pipenv
        run: make install

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: make init

      - name: Bump version
        run: make bump-minor

      - name: Run analyzer
        run: make analyze

      - name: Run test suite
        run: make tests

      - name: Upload test results (junit)
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: pytest-results
          path: junit/test-results.xml

      - name: Upload test results (html)
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: pytest-html
          path: htmlcov/

      - name: Package code
        run: make package

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: egg
          path: dist/

      - name: Deploy package to dev
        run: echo "DEPLOY TO DEV"